// <auto-generated />
namespace School.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class March4 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(March4));
        
        string IMigrationMetadata.Id
        {
            get { return "202103060404312_March4"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
