// <auto-generated />
namespace School.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class mrch5x2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(mrch5x2));
        
        string IMigrationMetadata.Id
        {
            get { return "202103062042564_mrch5x2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
