// <auto-generated />
namespace School.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class _4MAR21x2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_4MAR21x2));
        
        string IMigrationMetadata.Id
        {
            get { return "202103050039224_4MAR21x2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
